#!/bin/bash -x
#
# Send message to #general channel on star-vote.slack.com when RPi reboots.
# 
# Setup:
#   Create a symbolic link to /usr/local/bin.
#       `sudo ln -s /home/pi/VoteBox-v2/ping_slack /usr/local/bin`
#   Append this line to the crontab. (Open with `crontab -e`).
#       `@reboot ping_slack`

url="https://hooks.slack.com/services/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"



send_message() {
    message="$(hostname) rebooted with IP address(es): `
    `$(hostname --all-ip-addresses | sed -e 's/[[:space:]]*$//')."

    curl \
        -X POST \
        -H 'Content-type: application/json' \
        "${url}" \
        --data @- <<-EOF
    {
        "text": "${message}"
    }
	EOF
}

until send_message
do
    sleep 1
done

send_message
