#!/bin/bash
#
# Send message to #general channel on star-vote.slack.com when RPi reboots.

echo 'Sending "Raspberry Pi rebooted." to Slack.'
curl -X POST -H 'Content-type: application/json' --data '{"text":"Raspberry Pi rebooted."}' https://hooks.slack.com/services/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 --max-time 5
